<div class="row">

	<?php
		if($success == true)
		{
			?>
				<div class="col-lg-12">
					<div class="alert alert-success" role="alert">
						<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
						<?=$this->translate('Save successful.');?>
					</div>
				</div>
			<?php
		}
	?>

	<div id="btns" class="col-lg-12">
		<div class="btn-group pull-right">
			<a href="<?=$this->url('logs', array('action' => 'create'));?>" class="btn btn-default"><?=$this->translate('New Register');?></a>
			<a href="<?=$this->url('logs', array('action' => 'read'  ));?>" class="btn btn-default"><span class="glyphicon glyphicon-refresh"></span></a>
		</div>
	</div>
	
	<div id="grid" class="col-lg-12">
		<div class="panel panel-default">
			
			<div class="panel-heading">
				<?=$this->translate('Logs');?>
			</div>

			<div class="panel-body">
				<div class="alert alert-info" role="alert">
					<?=$this->translate('Log of use from registered lines in the system.');?>
				</div>
			</div>

			<?php
				
				if(count($logs) > 0)
				{
					?>

						<table class="table toggle-arrow-tiny" data-page-size="10" data-limit-navigation="4">
							<thead>
								<tr>
									<th>
										#
									</th>
									<th>
										<?=$this->translate('User');?>
									</th>
									<th>
										<?=$this->translate('Use');?>
									</th>
									<th>
										<?=$this->translate('Status');?>
									</th>
									<th>
										<?=$this->translate('Date and Time - Start');?>
									</th>
									<th>
										<?=$this->translate('Date and Time - End');?>
									</th>
								</tr>
							</thead>
							<tbody>

								<?php

									foreach($logs AS $key => $value)
									{
										?>
											<tr>
												<td><?=($key+1);?></td>
												<td><?=$this->escapeHtml((($value->usuario != null) ? $value->usuario : "---"));?></td>
												<td><?=$this->escapeHtml($value->utilizacao);?></td>
												<td><?=$this->escapeHtml($value->situacao);?></td>
												<td><?=$this->escapeHtml(date("d/m/Y h:i:s", strtotime($value->inicio)));?></td>
												<td><?=$this->escapeHtml((($value->final != null) ? date("d/m/Y h:i:s", strtotime($value->final)) : "---"));?></td>
											</tr>
										<?php
									}

								?>

							</tbody>
						</table>

					<?php

				}
				else
				{
					?>
							<table class="table table-bordered toggle-arrow-tiny" data-page-size="10" data-limit-navigation="4">
								<tr>
									<td align="center">
										<?=$this->translate('No record found.');?>
									</td>
								</tr>
							</table>
						<br />
						<br />
					<?php
				}
			?>

		</div>

		<div class="pull-left">
			<div class="current-page"></div>
		</div>
		<div class="pull-right">
			<ul class="pagination"></ul>
		</div>

	</div>

</div>